name: Rocket
author: Mauricius17 & Paul2708
version: Beta 4.0

main: de.mauricius17.rocket.system.Rocket

commands:
  rocket:
    description: Get rocket item
    usage: /rocket
  parachute:
    description: Get parachute item
    usage: /parachute

permissions:
  rocket.use:
    default: false
  parachute.use:
    default: false
  rocket.item:
    default: false
  parachute.item:
    default: false
  rocket.warp.list:
    default: false
  rocket.warp.set:
    default: false
  rocket.warp.remove:
    default: false
  rocket.warp.teleport:
    default: false